### ISSUE TITLE
CakePHP installation issue

### ISSUE THREAD

**Issue by koffisani** [loadsys/CakePHP-Sitemap#27] opened 2016-05-13 08:35 UTC
Got this exception trying to install on CakePHP 3.2+
`Generating autoload files
> Cake\Composer\Installer\PluginInstaller::postAutoloadDump
Script Cake\Composer\Installer\PluginInstaller::postAutoloadDump handling the post-autoload-dump event terminated with an exception
Installation failed, reverting ./composer.json to its original content.                                                                     
  [RuntimeException]                                                           
  Unable to get primary namespace for package loadsys/cakephp_sitemap.         
  Ensure you have added proper 'autoload' section to your plugin's config as   
  stated in README on https://github.com/cakephp/plugin-installer              
                                                                               
`
Is there any way to fix this ?

**Comment by beporter** [comment] 2016-05-13 14:42
Yes, there probably is a way to fix this. I suspect the problem is in our composer.json being out of date. We'll investigate as soon as we can. Probably Monday. Thanks for the report!

**Comment by beporter** [comment] 2016-05-13 14:43
Actually-- the reason may be that currently the master branch meant for Cake 2.x. We've started a branch for Cake 3 but I don't believe it is completed yet.

**Comment by justinyost** [comment] 2016-05-13 15:18
HI @koffisani,

Sorry for the troubles with this. This issue is due the plugin not currently working in Cake 3. There is a branch and PR in progress for this here: https://github.com/loadsys/CakePHP-Sitemap/pull/26

I don't have an expected timeline on when this will be ready, but I know you and other people are wanting to use this for your Cake 3 applications.

I'm going to close this issue as I don't think we can be of any further help as of right now.

**Closed by justinyost** 2016-05-13 15:18 UTC
Labels: bug, question
